### ISSUE TITLE
Feature: Post generated image to local TV server via Home Assistant automation

### ISSUE THREAD

**Issue by dipseth** [dipseth/react-image-generator#4]
## Feature Request

Allow this site to post a generated image to a local TV server using Home Assistant YAML automation. This will enable users to display generated images as notifications on Android TV devices or cast web content to the TV.

### Example YAML Automations

**pipup_image_on_tv:**
```yaml
pipup_image_on_tv:
  url: http://10.0.0.77:7979/notify
  content_type: "application/json"
  verify_ssl: false
  method: "post"
  timeout: 20
  payload: >
    {
      "duration": {{ duration | default(20) }},
      "position": {{ position | default(0) }},
      "title": "{{ title | default('') }}",
      "titleColor": "{{ titleColor | default('#50BFF2') }}",
      "titleSize": {{ titleSize | default(10) }},
      "message": "{{ message }}",
      "messageColor": "{{ messageColor | default('#fbf5f5') }}",
      "messageSize": {{ messageSize | default(14) }},
      "backgroundColor": "{{ backgroundColor | default('#0f0e0e') }}",
      "media": { 
        "image": {
          "uri": "{{ url }}",
          "width": {{ width | default(640) }}
        }
      }
    }
```

**pipup_url_on_tv:**
```yaml
pipup_url_on_tv:
  url: http://10.0.0.77:7979/notify
  content_type: "application/json"
  verify_ssl: false
  method: "post"
  timeout: 20
  payload: >
    {
      "duration": {{ duration | default(20) }},
      "position": {{ position | default(0) }},
      "title": "{{ title | default('') }}",
      "titleColor": "{{ titleColor | default('#50BFF2') }}",
      "titleSize": {{ titleSize | default(10) }},
      "message": "{{ message }}",
      "messageColor": "{{ messageColor | default('#fbf5f5') }}",
      "messageSize": {{ messageSize | default(14) }},
      "backgroundColor": "{{ backgroundColor | default('#0f0e0e') }}",
      "media": { 
        "web": {
          "uri": "{{ url }}", 
          "width": {{ width | default(640) }},
          "height": {{ height | default(480) }}
        }
      }
    }
```

### Requirements
- Add a feature to send a generated image (or web URL) to the TV server at the specified endpoint.
- Use the provided payload format and allow customization of fields as in the YAML.
- Integrate with Home Assistant automations for seamless smart home workflows.

---

**Hand off to architect for implementation plan.**
